site_name: Stretchy
theme: readthedocs
pages:
- ['index.md', 'Home']
- ['getting_started.md', 'Getting Started']
- ['reference/index.md', 'Reference']
- ['reference/index_operations.md', 'Reference', 'Index Operations']